#!/bin/bash
#
# Author: Alex Diaz <alex@akdev.xyz>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

export TOOLBOX_PATH="$(realpath "${BASH_SOURCE[0]}")"

exec podman run \
    --rm \
    -it \
    --security-opt label=disable \
    --userns=keep-id  \
    -e XDG_RUNTIME_DIR  \
    -e TOOLBOX_PATH \
    -e HOME \
    -e SHELL \
    -e USER \
    -w $PWD \
    -v /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket  \
    -v /run/user/$(id -u)/podman:/run/user/$(id -u)/podman \
    -v "$XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR" \
    -v "$HOME:$HOME" \
    -v "$PWD:$PWD" \
    docker.io/akdev1l/toolbox:slim "$@"
