#!/bin/bash
#
# Author: Alex Diaz <alex@akdev.xyz>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
TOOLBOX_IMAGE="docker.io/akdev1l/toolbox:slim"
TMP_TOOLBOX_PATH="/run/user/$(id -u)/toolbox"


if ! podman image exists "${TOOLBOX_IMAGE}"; then
	podman pull "${TOOLBOX_IMAGE}"
fi

if ! [ -f "${TMP_TOOLBOX_PATH}/bin/toolbox" ]; then
	PODMAN_IMAGE_PATH="$(podman unshare podman image mount "${TOOLBOX_IMAGE}")"
	podman unshare cp -rp "${PODMAN_IMAGE_PATH}/usr/local/bin" "${TMP_TOOLBOX_PATH}"
	echo "toolbox temporarily installed to ${TMP_TOOLBOX_PATH}/bin/toolbox"
fi

exec "${TMP_TOOLBOX_PATH}/bin/toolbox" "$@"
