---
- hosts: all
  tasks:
    - name: Install requirements
      become: yes
      package:
        use: apt
        name:
          - shellcheck
          - bash-completion
          - bats
          - flatpak
          - golang
          - golang-github-cpuguy83-md2man-v2-dev
          - apache2-utils
          - meson
          - ninja-build
          - openssl
          - podman
          - skopeo
          - systemd
          - udisks2

    - name: Setup submodules
      shell: |
        git submodule init
        git submodule update

    - name: Show podman versions
      command: podman version

    - name: Show podman debug information
      command: podman info --debug

    - name: Set up build directory
      command: meson builddir

    - name: Build Toolbox
      command: ninja -C builddir
      args:
        creates: builddir/src/toolbox

    - name: Install Toolbox
      become: yes
      command: ninja -C builddir install
      args:
        creates: /usr/local/bin/toolbox
