name: dev-build

on:
  push:
    branch: akdev
    paths:
      - "src/**"
      - "playbooks/**"
      - "test/**"
      - ".github/workflows/build-dev-release.yml"

jobs:
  build:
    name: build binaries
    runs-on: ubuntu-latest
    container:
      image: fedora:36
    steps:
      - uses: actions/checkout@v2
      - name: install build dependencies
        run: dnf install -y go meson go-md2man ShellCheck fish cmake podman
      - name: configure meson project
        run: meson builddir -Dinstall_completions=false
      - name: run ninja build
        run: ninja -C builddir
      - name: install for packaging purposes
        run: ninja -C builddir install
      - name: quick sanity test
        run: /usr/local/bin/toolbox --version
      - uses: actions/upload-artifact@v3
        with:
          name: toolbox
          path: /usr/local
      - uses: actions/upload-artifact@v3
        with:
          name: toolbox-bin
          path: /usr/local/bin/toolbox
  test:
    name: sanity test on ubuntu-latest
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: install ansible
        run: sudo apt install -y ansible && ls
      - name: setup testing environment
        run: ansible-playbook playbooks/setup-env.yaml -i localhost,
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
      - name: download toolbox artifact
        uses: actions/download-artifact@v3
        with:
          name: toolbox
          path: /tmp/toolbox
      - name: print downloaded file tree
        run: tree /tmp/toolbox
      - name: make sure toolbox binary is executable
        env:
          SHELL: /bin/bash
        run: chmod +x /tmp/toolbox/bin/toolbox
      - name: run system-test.yaml
        run: |
          echo 'export PATH="/tmp/toolbox/bin:$PATH"' | sudo tee /etc/profile.d/test-env.sh
          ansible-playbook playbooks/system-test.yaml -i localhost,
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
