name: dev-build

on:
  push:
    branch: akdev
    paths:
      - "src/**"
      - "playbooks/**"
      - "test/**"
      - ".github/workflows/build-dev-release.yml"

jobs:
  build:
    name: build binaries
    runs-on: ubuntu-latest
    container:
      image: fedora:36
    steps:
      - uses: actions/checkout@v2
      - name: install build dependencies
        run: dnf install -y go meson go-md2man ShellCheck fish cmake podman
      - name: configure meson project
        run: meson builddir
      - name: run ninja build
        run: ninja -C builddir test
      - name: install for packaging purposes
        run: ninja -C builddir install
      - name: quick sanity test
        run: /usr/local/bin/toolbox --version
      - uses: actions/upload-artifact@v3
        with:
          name: toolbox
          path: /usr/local
      - uses: actions/upload-artifact@v3
        with:
          name: toolbox-bin
          path: /usr/local/bin/toolbox
  test:
    name: sanity test on ubuntu-latest
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: install ansible
        run: apt install -y ansible
      - name: setup testing environment
        run: ansible-playbook playbooks/setup-env.yml
      - name: download toolbox artifact
        uses: actions/download-artifact@v3
        with:
          name: toolbox
          path: /usr/local
      - name: print downloaded file tree
        run: tree /usr/local
      - name: make sure toolbox binary is executable
        env:
          SHELL: /bin/bash
        run: chmod +x /usr/local/bin/toolbox
      - name: run system-test.yml
        run: ansible-playbook playbooks/system-test.yml
